//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.ServiceReference2 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertMethod", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertMethod(string id_stud, string id_dis, string date, string mark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertMethod", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InsertMethodAsync(string id_stud, string id_dis, string date, string mark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetData(string dateFirst, string dateSecond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetDataAsync(string dateFirst, string dateSecond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteRec", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DeleteRec(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteRec", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteRecAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNameStudSelectData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetNameStudSelectData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNameStudSelectData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetNameStudSelectDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDisSelectData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetDisSelectData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDisSelectData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetDisSelectDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecCheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RecCheck(string id_dis, string id_stud, string date, string ocenka);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecCheck", ReplyAction="*")]
        System.Threading.Tasks.Task<string> RecCheckAsync(string id_dis, string id_stud, string date, string ocenka);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebApplication.ServiceReference2.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebApplication.ServiceReference2.WebService1Soap>, WebApplication.ServiceReference2.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public string InsertMethod(string id_stud, string id_dis, string date, string mark) {
            return base.Channel.InsertMethod(id_stud, id_dis, date, mark);
        }
        
        public System.Threading.Tasks.Task<string> InsertMethodAsync(string id_stud, string id_dis, string date, string mark) {
            return base.Channel.InsertMethodAsync(id_stud, id_dis, date, mark);
        }
        
        public System.Data.DataTable GetData(string dateFirst, string dateSecond) {
            return base.Channel.GetData(dateFirst, dateSecond);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetDataAsync(string dateFirst, string dateSecond) {
            return base.Channel.GetDataAsync(dateFirst, dateSecond);
        }
        
        public void DeleteRec(string id) {
            base.Channel.DeleteRec(id);
        }
        
        public System.Threading.Tasks.Task DeleteRecAsync(string id) {
            return base.Channel.DeleteRecAsync(id);
        }
        
        public System.Data.DataTable GetNameStudSelectData() {
            return base.Channel.GetNameStudSelectData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetNameStudSelectDataAsync() {
            return base.Channel.GetNameStudSelectDataAsync();
        }
        
        public System.Data.DataTable GetDisSelectData() {
            return base.Channel.GetDisSelectData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetDisSelectDataAsync() {
            return base.Channel.GetDisSelectDataAsync();
        }
        
        public string RecCheck(string id_dis, string id_stud, string date, string ocenka) {
            return base.Channel.RecCheck(id_dis, id_stud, date, ocenka);
        }
        
        public System.Threading.Tasks.Task<string> RecCheckAsync(string id_dis, string id_stud, string date, string ocenka) {
            return base.Channel.RecCheckAsync(id_dis, id_stud, date, ocenka);
        }
    }
}
